sudo: required

services:
  - docker

before_install:
  - docker build -t test/planet-sympy .
  - docker ps -a

script:
  - bin/test_travis.sh

env:
  global:
    secure: "WQL7FM56HhRHulekVBMrQ6uj1dZOw44H2LGWCLZv/oq7KsaEVCXlRpJQCqHmOYuPiuut3JPwExA3/Zxn0sGZtdqVzj/woKnTnsiWxhLkeh34W7xj64sY6FvWKeDMKcmj7C2Ubmr0VcX8nmf13Fup92MI1LnmQSSTfsifInKge2gBmMOxGOQ3s2gdEzz+mTNSSQLFXI/izsSU9m0hraE9NYxHvpkkEsEfTMQfBlvBmkBK3Sfb5xWDMI5rV3tXUkuoGXDXHnqxAQLoUlAsRw/PxXzoard/6uE1J2sk7Qf8dv+AbokqD52ds/p2Sqhr2xQDOEeQT2Ib+vFfuXylQWWpOtsewWQFKFoi2T2RVvqrMrGuwGec4hPJdwTswe5KmCE4apu9ZevUXklKJkreMzyxlj3LTh1HadDKryIbbZOPp54FcJGZ6s+Rt3hYaKnnCTlsEA9vKBHpzv4FkHTboUCWX3pcPmyKQarhi4407bgf4gmjF8EShq5uDbGm/vqi/jBKmKqlQw7PZYbbeXOoepEuwaknmNJjLvT24flfSAmHgWH9Gv8nck3q6cigl3rCOzG5P8pHojphtc8XnJ77ryc6n2uJePHFOoI1hGE5mcFrT9/tt4oHInf7xFmqr1/0Q+K4fnlD9YazGXszczhAcctTdKtV5HvxbM3n37CKLLdm/hs="

notifications:
  email: false
