sudo: required

services:
  - docker

before_install:
  - docker build -t test/planet-sympy .
  - docker ps -a

script:
  - bin/test_travis.sh

env:
  global:
    secure: "rUdhcPW++uMHSRxHrBYphRjuHK1WsJgjRfPww4OvYQU/i9iAK+VQkQgpH6pCtj1uVNAVdAf3qomO8gF695Ar5gxp98U3ombrHxNswxNhq6HOUSFGAdetJWhUByWS+V4vIwc9j2ejP2u787j0yNe3jqgPIDCViAM9LStNu2vi9ig+6P0qIYf6r5/X8F3mVuvnos5L8YQ3yLpo5NLlD9GKdWjWXd6yjROfeUo2VdJSTDHHwmKeeT+As7PoACSYpH/ADqQmQKr0uEGXcQdz7XIrMyYcZoGqi47GsWWhY7fX4TFCwOY7YWJYGDVmPonsnlUNVJb5IXMnsYGYnJBNJiwQwFi693PExmjk+lfNk6IPcOYU5RLldELMy3mGKB72i3ukKlvLYp7r7r4eFfTwCuvfDrYcSK8Rfcy08CSLmIbKBVWUS9l1+gpAyWC94qgqU5j6q0S4CZWajhwx1QopTMUDXLOZRWYnkFy/+RPiFrigv42pinN+FYxffWiJH/NDQjpuuW06DrP9mf0k8Ju5LCwmB6mHkGCqXsl+uIrSfDxwykkTRkHCeVDNr6yrTWaeW6iegyFdcwf0gNjifhNDtk5Mw+I6n7T9Ncwg/01kEZ4Ahhk44Y54qxpKLP3b83gz3keepdZeLQG+IRInHhE97/c1Sv8kl1WMbqrULHaZ7AECAlk="

notifications:
  email: false
