sudo: required

services:
  - docker

before_install:
  - docker build -t test/planet-sympy .
  - docker ps -a

script:
  - bin/test_travis.sh

env:
  global:
    secure: "TPLfEEsWQlZaRTruo9iRTwk8GKvPHE7HXjKiNRM/1SwF4OfCqk0OUYKGkawnHJXnWccEljucXDkx4DHBXkca9I6eaYMAR9L6tC/3PKruGPMwwiPXk4wv7HzK/5H+EB5rcePURO+wRhu+2JpUU8QdMaMblsZ8cFu+TIXEHph2Q+TlmygYtvJK6IUxuzB3d6CcOlcoCeSPWCKfmWNEMidEVUMhoL17vfo0w0PChvRmzUlbPqRYjRZ6Zo5STr3O4+0pXqYg+LaBb+azWMiBneGQUWeKI5MBbt8xSVwSRdWQk1/anGnJTy+ZwgDZ+UB0c/LIQr5lAeVSabTF/qPloacKp38RvjOwdQGa9Iil+IJH0noP+ErB0vqiz5GNPqe/3d1M8bLh0eNoCQWxXLkNsfEAOldaERWYXnDDSfZqK4TN5njcEF0TDUfSbmJ22zNj+kQjQnU1np+u1nkgzEZEc40wUo0z+LSVq+gyWlSfVfIfrSJKxTPCQdbnmPrwKa6yDVU6GDabqBtrJuQus4oPkEK4j38VsnuBrkd82yqCw2qLh9u7b5+fm33yoQ2xBgLdF5kOWQwe1qhmT/NNi7pDOhn2350skJQ4uB/PMq9XTO3qTCl4ouRJpn8Nat1v8Yhl1WU/gLnlzbto0drWVLzCAh3KDS/EB5U78EVqtQQgb0n3JfY="

notifications:
  email: false
